# Generated by Django 5.2 on 2025-04-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='score',
        ),
    ]
