# Generated by Django 5.1.7 on 2025-04-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_genre_customuser_score_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
