# Generated by Django 5.2 on 2025-04-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_quizresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
