# Generated by Django 5.2 on 2025-04-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_quizresult_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='submission_time',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='user',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='is_correct',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_questions', models.IntegerField()),
                ('correct_count', models.IntegerField()),
                ('wrong_count', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quizresult',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.quizsession'),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
