# Generated by Django 5.1.7 on 2025-04-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_genre_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
