# Generated by Django 5.2 on 2025-04-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_quizresult_submission_time_quizsession_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='start_time',
        ),
    ]
