# Generated by Django 5.2 on 2025-04-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_quizsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
