# Generated by Django 5.2 on 2025-04-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_quizsession_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='subject',
        ),
    ]
