# Generated by Django 5.2 on 2025-05-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_quizsession_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='quiz_type',
            field=models.CharField(default='general', max_length=20),
            preserve_default=False,
        ),
    ]
