# Generated by Django 5.2 on 2025-05-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_quizsession_end_time_quizsession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
