# Generated by Django 5.2 on 2025-05-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_customuser_profile_image_customuser_solve_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='speed_score',
        ),
        migrations.AddField(
            model_name='customuser',
            name='speed_score_1min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='speed_score_3min',
            field=models.IntegerField(default=0),
        ),
    ]
