# Generated by Django 5.2 on 2025-06-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_questionstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstat',
            name='correct_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionstat',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
